version: 0.2

env:
  parameter-store:
    GPG_PASSPHRASE: "GPG_PASSPHRASE"

phases:
  install:
    commands:
      - aws s3 sync s3://vfro-cert/.gnupg ~/.gnupg
  build:
    commands:
      - mvn clean test site install -Dgpg.passphrase=$GPG_PASSPHRASE
cache:
  paths:
    - '~/.m2/**/*'
