version: 0.2

env:
  parameter-store:
    GPG_PASSPHRASE: "GPG_PASSPHRASE"

phases:
  install:
    commands:
      - aws s3 sync s3://vfro-cert/.gnupg ~/.gnupg
      - aws s3 sync s3://vfro-cert/.m2 ~/.m2
  build:
    commands:
      - mvn deploy -Dgpg.passphrase=$GPG_PASSPHRASE
cache:
  paths:
    - '~/.m2/repository/**/*'
