version: 0.2

phases:
  install:
    commands:
      - aws s3 sync s3://vfro-cert/.gnupg ~/.gnupg
      - aws s3 sync s3://vfro-cert/.m2 ~/.m2
  build:
    commands:
      - mvn site deploy
cache:
  paths:
    - '~/.m2/repository/**/*'
